#!/bin/bash

# Pre-commit hook to run static checks
# Mimic that tests run in the wrapup.yml flow in the GitHub workflow

PASS=TRUE


# Enable/disable specific checks
RUN_RUFF="FALSE"
RUN_PYTEST="FALSE"
RUN_CSPELL="TRUE"
RUN_MARKDOWNLINT="TRUE"
RUN_RAKE_HTMLPROOFER="TRUE"
RUN_RAKE_BUILD="TRUE"


echo "🔍 Running pre-commit checks..."


# Ruff check
if [ "$RUN_RUFF" == "TRUE" ]; then
    printf "   ⏳ Pytest with coverage\r"
    RUFF_OUT=$(ruff check --output-format=concise . 2>&1)

    if [ $? -eq 0 ]; then
        echo "   ✅ Ruff check"
    else
        echo "   ❌ Ruff check"
        PASS=FALSE
        RUFF=FALSE
    fi
fi

# Pytest with coverage
if [ "$RUN_PYTEST" == "TRUE" ]; then
    printf "   ⏳ Pytest with coverage\r"
    # Capture only STDERR (errors and summary), discard STDOUT (individual test progress)
    PYTEST_OUT=$(pytest --cov=. --cov-report= -m unittest --tb=no -q 2>&1)

    if [ $? -eq 0 ]; then
        echo "   ✅ Pytest with coverage"
    else
        echo "   ❌ Pytest with coverage"
        PASS=FALSE
        PYTEST=FALSE
    fi
fi

# Cspell
if [ "$RUN_CSPELL" == "TRUE" ]; then
    printf "   ⏳ CSpell check\r"
    CSPELL_OUT=$( cspell lint --no-progress 2>&1)

    if [ $? -eq 0 ]; then
        echo "   ✅ CSpell check"
    else
        echo "   ❌ CSpell check"
        PASS=FALSE
        CSPELL=FALSE
    fi
fi

#Markdownlint
if [ "$RUN_MARKDOWNLINT" == "TRUE" ]; then
    printf "   ⏳ MarkDown Lint check\r"
    MARKDOWNLINT_OUT=$( markdownlint-cli2 2>&1)

    if [ $? -eq 0 ]; then   
        echo "   ✅ MarkDown Lint check"
    else
        echo "   ❌ MarkDown Lint check"
        PASS=FALSE
        MARKDOWNLINT=FALSE
    fi
fi

# Jekyll build via rake task
if [ "$RUN_RAKE_BUILD" == "TRUE" ]; then
    printf "   ⏳ Jekyll build check\r"
    JEKYLL_BUILD_OUT=$(bundle exec rake jekyll:build 2>&1)

    if [ $? -eq 0 ]; then
        echo "   ✅ Jekyll build check"
    else
        echo "   ❌ Jekyll build check"
        PASS=FALSE
        JEKYLL_BUILD=FALSE
    fi
fi

# HTML proof via rake task
if [ "$RUN_RAKE_HTMLPROOFER" == "TRUE" ]; then
    printf "   ⏳ HTML proofer check\r"
#    HTMLPROOFER_OUT=$(bundle exec rake proofer:check 2>&1)
    HTMLPROOFER_OUT=$(bundle exec rake proofer:check_external 2>&1)

    if [ $? -eq 0 ]; then
        echo "   ✅ HTML proofer check"
    else
        echo "   ❌ HTML proofer check"
        PASS=FALSE
        HTMLPROOFER=FALSE
    fi
fi


if [ "$PASS" == "TRUE" ]; then
    exit 0
else
    echo ""
    if [ "$RUFF" == "FALSE" ]; then
        echo "Ruff issues:"
        echo "${RUFF_OUT}"
        echo ""
    fi
    if [ "$PYTEST" == "FALSE" ]; then
        echo "Pytest issues:"
        echo "${PYTEST_OUT}"
        echo ""
    fi
    if [ "$CSPELL" == "FALSE" ]; then
        echo "CSpell issues:"
        echo "${CSPELL_OUT}"
        echo ""
    fi
    if [ "$MARKDOWNLINT" == "FALSE" ]; then
        echo "MarkDown lint issues:"
        echo "${MARKDOWNLINT_OUT}"
        echo ""
    fi
    if [ "$VITEST_OUT" == "FALSE" ]; then
        echo "Vitest issues:"
        echo "${VITEST_OUT}"
        echo ""
    fi
    if [ "$JEKYLL_BUILD" == "FALSE" ]; then
        echo "Jekyll Build issues:"
        echo "${JEKYLL_BUILD_OUT}"
        echo ""
    fi
    if [ "$HTMLPROOFER" == "FALSE" ]; then
        echo "HTML Proofer issues:"
        echo "${HTMLPROOFER_OUT}"
        echo ""
    fi
    
    echo "👉  Fix the issues above before committing."
    echo "💡  You can run the same checks manually with: '.githooks/pre-commit'"
    exit 1
fi
